# Generated by Django 4.1.5 on 2023-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_orders_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(max_length=5000),
        ),
    ]
